// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALOObz6ebOnRtrV4mXBGJSl228wIHiLiE',
    appId: '1:919440517427:web:3ab4cc63f66c6cf9943646',
    messagingSenderId: '919440517427',
    projectId: 'driver-app-9ede9',
    authDomain: 'driver-app-9ede9.firebaseapp.com',
    databaseURL: 'https://driver-app-9ede9-default-rtdb.firebaseio.com',
    storageBucket: 'driver-app-9ede9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPt1Ieqj6zBTCGxATiDoOLZ8RoUxUbOho',
    appId: '1:919440517427:android:ca95903f61d6d5f0943646',
    messagingSenderId: '919440517427',
    projectId: 'driver-app-9ede9',
    databaseURL: 'https://driver-app-9ede9-default-rtdb.firebaseio.com',
    storageBucket: 'driver-app-9ede9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSJjeeHZYjFfUyIDPnBo94672C3WEdbdM',
    appId: '1:919440517427:ios:c549d4c0582638e9943646',
    messagingSenderId: '919440517427',
    projectId: 'driver-app-9ede9',
    databaseURL: 'https://driver-app-9ede9-default-rtdb.firebaseio.com',
    storageBucket: 'driver-app-9ede9.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAQ9uanry0Zd2S5VT_z8lLm6iPSB2kkOw',
    appId: '1:443765164125:ios:57767b2c1dee011711e5b4',
    messagingSenderId: '443765164125',
    projectId: 'driver-app-6f975',
    storageBucket: 'driver-app-6f975.firebasestorage.app',
    databaseURL: 'https://driver-app-6f975-default-rtdb.firebaseio.com',
    iosBundleId: 'com.ttd.driverapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALOObz6ebOnRtrV4mXBGJSl228wIHiLiE',
    appId: '1:919440517427:web:b83bcd208b26961b943646',
    messagingSenderId: '919440517427',
    projectId: 'driver-app-9ede9',
    authDomain: 'driver-app-9ede9.firebaseapp.com',
    databaseURL: 'https://driver-app-9ede9-default-rtdb.firebaseio.com',
    storageBucket: 'driver-app-9ede9.firebasestorage.app',
  );

}